# Generated by Django 4.2.30 on 2026-05-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatorsync', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatorprofile',
            old_name='follower_count',
            new_name='followers',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='social_link',
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='instagram',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='tiktok',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
